barcode_app/urls.py
from django.urls import path
from barcode_app import views

app_name = 'barcode_app'
urlpatterns = [
    path('barcode_generate/', views.barcode_view, name='barcode_generate'),
    path('barcode_generate_done/', views.barcode_done_view, name='barcode_generate_done'),
    path('del_barcode_data/<int:id>/', views.del_barcode_data, name='del_barcode_data'),
]

qrcode_app/urls.py
from django.urls import path
from qrcode_app import views

app_name = 'qrcode_app'
urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('generated_data/', views.generated_data, name='generated_data'),
    path('delete_qrcode_data/<int:id>/', views.del_qrcode_data, name='del_qrcode_data'),
    path('qrcode_generate/', views.qr_code_view, name='qrcode_generate'),
    path('qrcode_generate_done/', views.qrcode_done_view, name='qrcode_done')
]

qrcode_barcode_generator_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('qrcode/', include('qrcode_app.urls', namespace='qrcode_app')),
    path('barcode/', include('barcode_app.urls', namespace='barcode_app')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

barcode_app/models.py
from django.db import models
import barcode
from barcode.writer import ImageWriter
from io import BytesIO
from django.core.files import File



class Barcode_Model(models.Model):
    name = models.CharField(max_length=200)
    barcode_name = models.ImageField(upload_to='Barcode_Images/%Y/%m/%d', blank=True)
    country_id = models.CharField(max_length=3, null=True)
    manufacturer_id = models.CharField(max_length=5, null=True)
    number_id = models.CharField(max_length=4, null=True)

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        EAN = barcode.get_barcode_class('ean13')
        ean = EAN(f'{self.country_id}{self.manufacturer_id}{self.number_id}', writer=ImageWriter)
        # ean = EAN('5901234123457', writer=ImageWriter)
        buffer = BytesIO()
        ean.writer(buffer)
        self.barcode_name.save(f'{self.name}.png', File(buffer), save=False)
        return super().save(*args, **kwargs)

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

qrcode_app/models.py
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw


class QR_Code_Model(models.Model):
    name = models.CharField(max_length=200)
    qrcode_name = models.ImageField(upload_to='QR_Code_Images/%Y/%m/%d', blank=True)

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        qrcode_img = qrcode.make(self.name)
        canvas = Image.new('RGB', (290, 290), 'white')
        draw = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname = f'qr_code-{self.name}' + '.png'
        buffer = BytesIO()
        canvas.save(buffer, 'PNG')
        self.qrcode_name.save(fname, File(buffer), save=False)
        return super().save(*args, **kwargs)

barcode_app/forms.py
from django import forms
from .models import Barcode_Model


class BarcodeModelForm(forms.ModelForm):
    class Meta:
        model = Barcode_Model
        fields = ['name', 'country_id', 'manufacturer_id', 'number_id']

qrcode_app/forms.py
from django import forms
from .models import QR_Code_Model


class qrcode_form(forms.ModelForm):
    class Meta:
        model = QR_Code_Model
        fields = ('name',)

barcode_app/views.py
from django.shortcuts import render
from .forms import BarcodeModelForm
from django.http import HttpResponseRedirect
from .models import Barcode_Model


def barcode_view(request):
    if request.method == 'POST':
        form = BarcodeModelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/barcode/barcode_generate_done')
    else:
        form = BarcodeModelForm()
    return render(request, 'barcode/barcode.html', {'form': form})


def del_barcode_data(request, id):
    if request.method == 'POST':
        dl = Barcode_Model.objects.get(pk=id)
        dl.delete()
        return HttpResponseRedirect('/qrcode/generated_data')


def barcode_done_view(request):
    return render(request, 'barcode/barcode_done.html')

qrcode_app/views.py
from django.shortcuts import render
from .forms import qrcode_form
from django.http import HttpResponseRedirect
from barcode_app.models import Barcode_Model
from qrcode_app.models import QR_Code_Model
from django.contrib import messages


def home_view(request):
    return render(request, 'main.html')


def generated_data(request):
    barcode_data = Barcode_Model.objects.all()
    qrcode_data = QR_Code_Model.objects.all()
    return render(request, 'generated_data.html', {'brdata': barcode_data, 'qrdata': qrcode_data})


def del_qrcode_data(request, id):
    if request.method == 'POST':
        dl = QR_Code_Model.objects.get(pk=id)
        dl.delete()
        messages.warning(request, 'Successfully Deleted you Qrcode...!!')
        return HttpResponseRedirect('/qrcode/generated_data')


def qr_code_view(request):
    if request.method == 'POST':
        form = qrcode_form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/qrcode/qrcode_generate_done')
    else:
        form = qrcode_form()
    return render(request, 'qrcode/qrcode.html', {'form': form})


def qrcode_done_view(request):
    return render(request, 'qrcode/qrcode_done.html')

qrcode_app/templates/barcode/barcode.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>Barcode Page</title>
    <style>
        *{
            font-family:Times New Roman;
        }
        h4{
            text-align: center;
        }


    </style>
</head>
<body>
<div class="container mt-3">
    <form method="POST" enctype="multipart/form-data">
        <h4 class="alert alert-success">Generate Barcode Using Python - Django </h4>
        {% csrf_token %}
        {{ form | crispy }}
        <p>
            <input type="submit" class="btn btn-success" value="Submit">
            <a href="{% url 'qrcode_app:qrcode_generate' %}">do you want to generate Qrcode ?</a>
        </p>
    </form>
</div>
</body>
</html>

qrcode_app/templates/barcode/barcode_done.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    Thank You
    {% endblock title %}
</head>
<body>
{% block content %}
<div class="container text-center">
    <p>
        <img src="{% static 'image/thank_you.jpg' %}" class="img-thumbnail">
    </p>
    <h4 class="alert alert-success">You have Successfully Generated your Barcode....!! </h4>
    <center><a href="{% url 'qrcode_app:home' %}" class="btn btn-success">Back to Home</a></center>
</div>
{% endblock content %}
</body>
</html>

qrcode_app/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>
        Qrcode Barcode Generator |
        {% block title %}
        {% endblock title %}
    </title>
    <style>
        *{
            font-family: Times New Roman;
        }
        h4{
            text-align:center;
        }

    </style>
</head>
<body>
<div class="mt-3">
    {% block content %}

    {% endblock content %}
</div>
</body>
</html>

qrcode_app/templates/generated_data.html
<!DOCTYPE html>
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    Generated Data
    {% endblock title %}
</head>
<body>
{% block content %}
<div class="row">
    <div class="col-sm-5">
        {% if messages %}
        {% for msg in messages %}
        <h4 class="alert alert-danger">{{ msg }}</h4>
        {% endfor %}
        {% else %}
        <h4 class="alert alert-success">Qrcode Generated List</h4>
        {% endif %}
        <table class="table table-hover">
            {% if qrdata %}
            <thead class="text-center">
            <th>No</th>
            <th>Name</th>
            <th>Qrcode Image</th>
            <th>Action</th>
            </thead>
            <tbody class="text-center">
            {% for qr in qrdata %}
            <tr>
                <td>{{ qr.id }}</td>
                <td>{{ qr.name }}</td>
                <td>
                    <a href="{{ qr.qrcode_name.url }}">
                        <img class="img-thumbnail" src="{{ qr.qrcode_name.url }}" width="20%" height="20%">
                    </a>
                </td>
                <td>
                    <form method="post" action="{% url 'qrcode_app:del_qrcode_data' qr.id %}">
                        {% csrf_token %}
                        <input class="btn btn-warning btn-sm" type="submit" value="Delete">
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
            {% else %}
            <h3>No Record Found....!!</h3>
            {% endif %}
        </table>
    </div>
    <div class="col-sm-7">
        <h4 class="alert alert-success">Barcode Generated List</h4>
        <table class="table table-hover">
            {% if brdata %}
            <thead class="text-center">
            <th>No</th>
            <th>Name</th>
            <th>Country_id</th>
            <th>Mannuf_id</th>
            <th>Number_id</th>
            <th>Image</th>
            <th>Action</th>
            </thead>
            <tbody class="text-center">
            {% for br in brdata %}
            <tr>
                <td>{{ br.id }}</td>
                <td>{{ br.name }}</td>
                <td>{{ br.country_id }}</td>
                <td>{{ br.manufacturer_id }}</td>
                <td>{{ br.number_id }}</td>
                <td>
                    <img src="{{ br.barcode_name.url }}">
                </td>
                <td>
                    <form method="post" action="{% url 'barcode_app:del_barcode_data' br.id %}">
                        {% csrf_token %}
                        <input class="btn btn-warning btn-sm" type="submit" value="Delete">
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
            {% else %}
            <h3>No Record Found...!!</h3>
            {% endif %}
        </table>
    </div>
</div>
<center><a href="{% url 'qrcode_app:home' %}" class="btn btn-success">Back to Home</a></center>
{% endblock content %}
</body>
</html>

qrcode_app/templates/main.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>
        Qrcode Barcode Generator
        {% block title %}
        {% endblock title %}
    </title>
    <style>
        *{
            font-family: Times New Roman;
        }
        h4{
            text-align:center;
        }
    </style>
</head>
<body>
<div class="container mt-3">
    <h4 class="alert alert-success"> Welcome to QR-Code and Barcode Generator</h4>
    <center>
        <a href="{% url 'qrcode_app:qrcode_generate' %}" class="btn btn-success">Generate QR-Code</a>
        <a href="{% url 'barcode_app:barcode_generate' %}" class="btn btn-success">Generate Barcode</a>
    </center><br><br><br><br>
    <center>
        <a href="{% url 'qrcode_app:generated_data' %}" class="btn btn-warning">View Generated Data</a>
    </center>
    {% block content %}

    {% endblock content %}
</div>
</body>
</html>

qrcode_app/templates/qrcode/qrcode.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    Qrcode Generator
    {% endblock title %}
</head>
<body>
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <h4 class="alert alert-success">Generate QR-Code Using Python - Django</h4>
        {% csrf_token %}
        {{ form | crispy }}
        <p>
            <input type="submit" value="Submit" class="btn btn-success">
            <a href="{% url 'barcode_app:barcode_generate' %}">do you want to generate Barcode ?</a>
        </p>
    </form>
</div>
{% endblock content %}
</body>
</html>

qrcode_app/templates/qrcode/qrcode_done.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    Thank You
    {% endblock title %}
</head>
<body>
{% block content %}
<div class="container text-center">
    <p>
        <img src="{% static 'image/thank_you.jpg' %}" class="img-thumbnail">
    </p>
    <h4 class="alert alert-success">You have Successfully Generated your QR_Code....!! </h4>
    <center><a href="{% url 'qrcode_app:home' %}" class="btn btn-success">Back to Home</a></center>
</div>
{% endblock content %}
</body>
</html>